mapeamento_acentos = {
    "Afeganistao": "Afeganistão",
    "Africa do Sul": "África do Sul",
    "Albania": "Albânia",
    "Alemanha": "Alemanha",
    "Andorra": "Andorra",
    "Angola": "Angola",
    "Anguilla": "Anguilla",
    "Antarctica": "Antárctica",
    "Antigua e Barbuda": "Antigua e Barbuda",
    "Antilhas Holandesas": "Antilhas Holandesas",
    "Arabia Saudita": "Arábia Saudita",
    "Argelia": "Argélia",
    "Argentina": "Argentina",
    "Armenia": "Armênia",
    "Aruba": "Aruba",
    "Australia": "Austrália",
    "Austria": "Áustria",
    "Azerbaijao": "Azerbaijão",
    "Bahamas": "Bahamas",
    "Bangladesh": "Bangladesh",
    "Barbados": "Barbados",
    "Barein": "Barein",
    "Belarus": "Belarus",
    "Belgica": "Bélgica",
    "Belize": "Belize",
    "Benin": "Benin",
    "Bermuda": "Bermuda",
    "Bolivia": "Bolívia",
    "Bosnia e Herzegovina": "Bósnia e Herzegóvina",
    "Botswana": "Botswana",
    "Brasil": "Brasil",  # já está correto
    "Brunei": "Brunei",
    "Bulgaria": "Bulgária",
    "Burkina Fasso": "Burkina Fasso",
    "Burundi": "Burundi",
    "Butao": "Butão",
    "Cabo Verde": "Cabo Verde",
    "Camaroes": "Camarões",
    "Camboja": "Camboja",
    "Canada": "Canadá",
    "Catar": "Catar",
    "Cazaquistao": "Cazaquistão",
    "Chade": "Chade",
    "Chile": "Chile",
    "China": "China",
    "Chipre": "Chipre",
    "Cingapura": "Cingapura",
    "Colombia": "Colômbia",
    "Comores": "Comores",
    "Congo": "Congo",
    "Coreia do Norte": "Coréia do Norte",
    "Coreia do Sul": "Coréia do Sul",
    "Costa do Marfim": "Costa do Marfim",
    "Costa Rica": "Costa Rica",
    "Croacia": "Croácia",
    "Cuba": "Cuba",
    "Dinamarca": "Dinamarca",
    "Djibuti": "Djibuti",
    "Dominica": "Dominica",
    "Egito": "Egito",
    "El Salvador": "El Salvador",
    "Emirados Arabes Unidos": "Emirados Árabes Unidos",
    "Equador": "Equador",
    "Eritreia": "Eritréia",
    "Eslovaquia": "Eslováquia",
    "Eslovenia": "Eslovênia",
    "Espanha": "Espanha",  # já está correto
    "Estado da Palestina": "Estado da Palestina",
    "Estados Unidos": "Estados Unidos",
    "Estonia": "Estônia",
    "Etiopia": "Etiópia",
    "Federacao Russa": "Federação Russa",
    "Fiji": "Fiji",
    "Filipinas": "Filipinas",
    "Finlandia": "Finlândia",
    "Franca": "França",
    "Franca Metropolitana": "França Metropolitana",
    "Gabao": "Gabão",
    "Gambia": "Gâmbia",
    "Gana": "Gana",
    "Georgia": "Geórgia",
    "Gibraltar": "Gibraltar",
    "Gra-Bretanha": "Grã-Bretanha",
    "Granada": "Granada",
    "Grecia": "Grécia",
    "Groenlandia": "Groenlândia",
    "Guadalupe": "Guadalupe",
    "Guam": "Guam",
    "Guatemala": "Guatemala",
    "Guiana": "Guiana",
    "Guiana Francesa": "Guiana Francesa",
    "Guine": "Guiné",
    "Guine-Bissau": "Guiné-Bissau",
    "Guine Equatorial": "Guiné Equatorial",
    "Haiti": "Haiti",
    "Holanda": "Holanda",
    "Honduras": "Honduras",
    "Hong Kong": "Hong Kong",
    "Hungria": "Hungria",
    "Iemen": "Iêmen",
    "Ilha Bouvet": "Ilha Bouvet",
    "Ilha Christmas": "Ilha Christmas",
    "Ilha Norfolk": "Ilha Norfolk",
    "Ilhas Cayman": "Ilhas Cayman",
    "Ilhas Cocos": "Ilhas Cocos",
    "Ilhas Cook": "Ilhas Cook",
    "Ilhas Faroe": "Ilhas Faroe",
    "Ilhas Georgia do Sul e Ilhas Sandwich do Sul": "Ilhas Geórgia do Sul e Ilhas Sandwich do Sul",
    "Ilhas Guernsey": "Ilhas Guernsey",
    "Ilhas Heard e Mac Donald": "Ilhas Heard e Mac Donald",
    "Ilhas Malvinas": "Ilhas Malvinas",
    "Ilhas Mariana": "Ilhas Mariana",
    "Ilhas Marshall": "Ilhas Marshall",
    "Ilhas Pitcairn": "Ilhas Pitcairn",
    "Ilhas Reuniao": "Ilhas Reunião",
    "Ilhas Salomao": "Ilhas Salomão",
    "Ilhas Santa Helena": "Ilhas Santa Helena",
    "Ilhas Svalbard e Jan Mayen": "Ilhas Svalbard e Jan Mayen",
    "Ilhas Tokelau": "Ilhas Tokelau",
    "Ilhas Turks e Caicos": "Ilhas Turks e Caicos",
    "Ilhas Virgens": "Ilhas Virgens",
    "Ilhas Virgens Britanicas": "Ilhas Virgens Britânicas",
    "Ilhas Wallis e Futuna": "Ilhas Wallis e Futuna",
    "India": "Índia",
    "Indonesia": "Indonésia",
    "Iran": "Irã",
    "Iraque": "Iraque",
    "Irlanda": "Irlanda",
    "Islandia": "Islândia",
    "Israel": "Israel",
    "Italia": "Itália",
    "Iugoslavia": "Iugoslávia",
    "Jamaica": "Jamaica",
    "Japao": "Japão",
    "Jersey": "Jersey",
    "Jordania": "Jordânia",
    "Kiribati": "Kiribati",
    "Kuweit": "Kuweit",
    "Laos": "Laos",
    "Lesoto": "Lesoto",
    "Letonia": "Letônia",
    "Libano": "Líbano",
    "Liberia": "Libéria",
    "Libia": "Líbia",
    "Liechtenstein": "Liechtenstein",
    "Lituania": "Lituânia",
    "Luxemburgo": "Luxemburgo",
    "Macau": "Macau",
    "Macedonia": "Macedônia",
    "Madagascar": "Madagascar",
    "Malasia": "Malásia",
    "Malaui": "Malauí",
    "Maldivas": "Maldivas",
    "Mali": "Mali",
    "Malta": "Malta",
    "Marrocos": "Marrocos",
    "Martinica": "Martinica",
    "Mauricio": "Maurício",
    "Mauritania": "Mauritânia",
    "Mayotte": "Mayotte",
    "Mexico": "México",
    "Mianmar": "Mianmar",
    "Micronesia": "Micronésia",
    "Mocambique": "Moçambique",
    "Moldavia": "Moldávia",
    "Monaco": "Mônaco",
    "Mongolia": "Mongólia",
    "Montenegro": "Montenegro",
    "Montserrat": "Montserrat",
    "Namibia": "Namíbia",
    "Nauru": "Nauru",
    "Nepal": "Nepal",
    "Nicaragua": "Nicarágua",
    "Niger": "Níger",
    "Nigeria": "Nigéria",
    "Niue": "Niue",
    "Noruega": "Noruega",
    "Nova Caledonia": "Nova Caledônia",
    "Nova Zelandia": "Nova Zelândia",
    "Oma": "Omã",
    "Palau": "Palau",
    "Panama": "Panamá",
    "Papua Nova Guine": "Papua Nova Guiné",
    "Paquistao": "Paquistão",
    "Paraguai": "Paraguai",
    "Peru": "Peru",
    "Polinesia Francesa": "Polinésia Francesa",
    "Polonia": "Polônia",
    "Porto Rico": "Porto Rico",
    "Portugal": "Portugal",
    "Quenia": "Quênia",
    "Quirguizia": "Quirguízia",
    "Republica Centro-Africana": "República Centro-Africana",
    "Republica Democratica do Congo": "República Democrática do Congo",
    "Republica Dominicana": "República Dominicana",
    "Republica Tcheca": "República Tcheca",
    "Romenia": "Romênia",
    "Ruanda": "Ruanda",
    "Sahara Ocidental": "Sahara Ocidental",
    "Samoa Americana": "Samoa Americana",
    "Samoa Ocidental": "Samoa Ocidental",
    "San Marino": "San Marino",
    "Santa Lucia": "Santa Lúcia",
    "Sao Cristovao e Nevis": "São Cristóvão e Névis",
    "Sao Pierre e Miquelon": "São Pierre e Miquelon",
    "Sao Tome e Principe": "São Tomé e Príncipe",
    "Sao Vicente e Granadinas": "São Vicente e Granadinas",
    "Seicheles": "Seicheles",
    "Senegal": "Senegal",
    "Serra Leoa": "Serra Leoa",
    "Servia": "Sérvia",
    "Siria": "Síria",
    "Somalia": "Somália",
    "Sri Lanka": "Sri Lanka",
    "Suazilandia": "Suazilândia",
    "Sudao": "Sudão",
    "Suecia": "Suécia",
    "Suica": "Suíça",
    "Suriname": "Suriname",
    "Tadjiquistao": "Tadjiquistão",
    "Tailandia": "Tailândia",
    "Taiwan": "Taiwan",
    "Tanzania": "Tanzânia",
    "Territorios Franceses Meridionais": "Territórios Franceses Meridionais",
    "Timor Leste": "Timor Leste",
    "Togo": "Togo",
    "Tonga": "Tonga",
    "Trinidad e Tobago": "Trinidad e Tobago",
    "Tunisia": "Tunísia",
    "Turcomenia": "Turcomênia",
    "Turquia": "Turquia",
    "Tuvalu": "Tuvalu",
    "Ucrania": "Ucrânia",
    "Uganda": "Uganda",
    "Uruguai": "Uruguai",
    "Uzbequistao": "Uzbequistão",
    "Vanuatu": "Vanuatu",
    "Vaticano": "Vaticano",
    "Venezuela": "Venezuela",
    "Vietna": "Vietnã",
    "Zambia": "Zâmbia",
    "Zimbabue": "Zimbábue"
}

def obter_pais_com_acento(nome_pais):
    return mapeamento_acentos.get(nome_pais, nome_pais)